"""
agents/writer.py
================
AGENT 4 — The Writer

WHAT IT DOES:
  Takes the structured insights from the Analyst and compiles them
  into a professional, well-formatted research report in markdown.

  If the human reviewer left feedback, the Writer incorporates it.

HOW TO EXPLAIN TO HR:
  "The Writer receives clean insights from the Analyst — not raw
   scraped content — and focuses entirely on producing a polished,
   professional report. It also reads the human reviewer's feedback
   from the HITL gate and incorporates it. This separation means
   I can improve report quality just by changing the Writer's prompt,
   without touching research or analysis logic."

Input  → state["structured_insights"], state["topic"],
         state["human_feedback"]
Output → state["draft_report"]
"""

import os
from dotenv import load_dotenv
from langchain_groq import ChatGroq
from langchain_core.messages import SystemMessage, HumanMessage
from graph.state import AppState

load_dotenv()

# ── LLM setup ─────────────────────────────────────────────────────────────────
llm = ChatGroq(
    model="llama-3.3-70b-versatile",
    temperature=0.2,          # slightly creative for better writing
    api_key=os.getenv("GROQ_API_KEY"),
)


def _build_writer_prompt(
    topic:    str,
    insights: list[str],
    feedback: str,
) -> str:
    """Build the prompt for the Writer agent."""

    all_insights = "\n\n".join(insights)

    feedback_block = ""
    if feedback and feedback.strip():
        feedback_block = f"\n\n⚠️ Reviewer feedback to incorporate:\n{feedback}"

    return f"""You are writing a professional research report.

Topic: {topic}
{feedback_block}

Structured Insights from Research:
{all_insights}

Write the report using EXACTLY this structure:

# {topic} — Research Report

## Executive Summary
[3-4 sentences capturing the most critical findings]

## Key Findings
[5-7 bullet points with the most important facts and numbers]

## Detailed Analysis

[One section per research subtask. Use ## headers.
Each section: 2-3 paragraphs using the insights provided.]

## Conclusion
[2-3 sentences: what this means and what to do about it]

## Sources Consulted
[Note: X sources consulted across Y research areas]

---
*Report generated by Multi-Agent Research System*
*Status: PENDING FACT-CHECK*"""


def writer_agent(state: AppState) -> dict:
    """
    MAIN FUNCTION — called by LangGraph as a node.

    Reads:  state["topic"], state["structured_insights"],
            state["human_feedback"]
    Writes: state["draft_report"]
    """

    # Only runs if human approved the insights
    if not state.get("human_approved", False):
        return {"draft_report": "Report not generated — insights were not approved."}

    prompt = _build_writer_prompt(
        topic    = state["topic"],
        insights = state["structured_insights"],
        feedback = state.get("human_feedback", ""),
    )

    response = llm.invoke([
        SystemMessage(content="You are an expert research writer. Write clear, specific, well-structured reports."),
        HumanMessage(content=prompt),
    ])

    return {"draft_report": response.content}
